### ISSUE TITLE
tf_to_path not working for static child_frame

### ISSUE THREAD

**Issue by peci1** [tpet/nav_utils#5]
The following logic blocks execution when the child frame is e.g. a static transform to another moving frame. Is there a reason for this logic at all? Could this behavior be changed to be enabled only when a parameter is set or so? @petrapa6 @kratkvit 

https://github.com/tpet/nav_utils/blob/9acc409512a168854fe0d98bc22d4c3ace757d4c/src/nav_utils/tf_to_path.cpp#L70-L82

**Comment by peci1** [comment]
Solution proposed in #6

**Comment by petrapa6** [comment]
Hey, sorry for the late reply. Thanks for updating the node in #6! I agree with the changes, the previous logic was written for the needs of the competition itself, where we shared dynamic transforms only and hence the logic did not take the child frames of static TFs into account.
